### ISSUE TITLE
How much is Pangeo Forge Cloud costing?

### ISSUE THREAD

**Issue by rabernat** [pangeo-forge/pangeo-forge-orchestrator#128]
I was on our Google Cloud Console this morning, so I thought I'd share some of the cost metrics for this project.

![Screen Shot 2022-09-16 at 9 34 37 AM](https://user-images.githubusercontent.com/1197350/190651315-4453c5ea-e7c7-40a5-8da8-8d8f81a07b14.png)

![Screen Shot 2022-09-16 at 9 34 51 AM](https://user-images.githubusercontent.com/1197350/190651377-11218cb3-f4d0-4800-af77-57959a369a61.png)

Overall the costs seem pretty reasonable! 🎉 

Going forward, we should make sure we are not paying egress charges to flux data to OSN. The OSN <> Google Cloud connection should be covered by the [Internet2 Egress Waiver](https://cloud.google.com/billing/docs/how-to/egress-waiver). But we need to confirm this.

**Comment by yuvipanda** [comment]
I just looked at this again: 

![image](https://user-images.githubusercontent.com/30430/204617294-f3b1181e-302d-43d8-bc6f-26759e1471d1.png)


@rabernat so our networking charges are all from NAT gateway, which is because we are forced to use private IPs. Thus, talking to external internet in any way costs $$$, and causes reliability & perf problems (due to limited outgoing IP use). Private IPs give us specifically no security advantages. 

In october we paid more in network charges than in compute or storage!

**Comment by cisaacstern** [comment]
> In october we paid more in network charges than in compute or storage!

Wow.
