### ISSUE TITLE
Replace homespun `config.py` with `traitlets` 

### ISSUE THREAD

**Issue by cisaacstern** [pangeo-forge/pangeo-forge-orchestrator#195]
Conversations with @andersy005 and @yuvipanda  this week surfaced the following items as high priority:

- **Developer experience**: local instances are toilsome to start (too much custom config fiddling required). And more generally, there is too much divergence in how the various instance types (local, containerized local, Heroku) are started, adding friction to development cycle.
- #150

These two items are actually related. A remaining blocker for #150 is a method for inspecting retrieved logs for leaked secrets. To do so, we will want to know what secrets are _potentially_ in the logs, so we can check for them specifically. An [overly-complex approach to this is in the existing PR](https://github.com/pangeo-forge/pangeo-forge-orchestrator/pull/150/files#diff-192396989739dc4bd56a22df41c827d4bc29df19ed4f4b03676b22c1833ea841R50-R71). This is a sufficiently awkward bit of code, that I think it's better to address the root issue (a more manageable application config), before circling back to #150.

A `traitlets`-based config will resolve the developer experience challenges in the same manner [as it does for binderhub](https://github.com/jupyterhub/binderhub/tree/main/testing) (thanks to Yuvi for this link). Just as jupyterhub can be run with

[`jupyterhub --config=jupyterhub_config.py`](https://github.com/jupyterhub/binderhub/tree/main/testing/local-binder-local-hub#readme) 

so too will the orchestrator API be runnable via a single command, with config for different instance types specified via a `--config` option pointing to a python config file. This should remove the need for separate entrypoints for local non-containerized instances (no entrypoint script currently exists for this), [local containerized (i.e. test/dev) instances](https://github.com/pangeo-forge/pangeo-forge-orchestrator/blob/fb5caaf6994d1b73004b447ab00e5687ab941f2e/docker-compose.yml#L34-L45), and [Heroku container stack (i.e. prod) instances](https://github.com/pangeo-forge/pangeo-forge-orchestrator/blob/fb5caaf6994d1b73004b447ab00e5687ab941f2e/heroku.yml#L18-L31). So switching between these instances should be as simple as:

```
$ pf-orchestrator --config=$INSTANCE_CONFIG_FILE
```

A secondary goal will be to make the bakeries config associated with each of these instances more easily accessible from within the application (for use cases such as needed for #150, as described above) and extensible, which will move us towards a solution to supersede #129. On this latter point, presumably the fact that `pangeo-forge-runner` uses `traitlets` means that configuring it _from_ a `traitlets` application will be easier than it is now.

Yuvi helped me see that the callable to which `pangeo-forge-runner` commands are passed can and should be a customizable part of this config. Currently, all runner commands are passed to `subprocess`. If this becomes part of the config, each instance config can define the callable to which it wants runner commands passed. This will remain `subprocess` for local instances, but can be configured to be a docker sibling container for the eventual (post-Heroku) deployment which uses isolated containers for recipe parsing.

cc @rabernat

**Comment by yuvipanda** [comment]
A more concrete example of making the way pangeo-forge-runner is called be generalizable via traitlets is how JupyterHub has a 'spawner' interface that allows it to run on so many places (locally, systemd, docker, HPC, kubernetes) without having internal knowledge of it all.

There's a base class Spawner (https://github.com/jupyterhub/jupyterhub/blob/5ea93add289f9905e4957f8a1a8d6d01ce5ab634/jupyterhub/spawner.py#L74) that is implemented by various subclasses:

1. [LocalProcessSpawner](https://github.com/jupyterhub/jupyterhub/blob/5ea93add289f9905e4957f8a1a8d6d01ce5ab634/jupyterhub/spawner.py#L1473), in the same package, that uses subprocess
2. [KubeSpawner](https://github.com/jupyterhub/kubespawner/blob/main/kubespawner/spawner.py) that talkt to kubernetes
3. [DockerSpawner](https://github.com/jupyterhub/dockerspawner/blob/main/dockerspawner/dockerspawner.py) that talks to docker API

And so many more. This allows the core JupyterHub code to remain compact and not have to be tied into the details of individiual spawning systems, and makes local development much easier, as you can just use a local spawner and do rapid development there with minimal overhead.

Config can pick which spawner to use via a `c.JupyterHub.spawner_class` config, read like [this](https://github.com/jupyterhub/jupyterhub/blob/5ea93add289f9905e4957f8a1a8d6d01ce5ab634/jupyterhub/app.py#L1194). Note that JupyterHub does some convenience methods that allow specifying a value from entrypoint (so you can set it to `kubespawner` rather than `kubespawner.KubeSpawner` - the former is a short string specified in `setup.py` of kubespawner, latter is class name). We can just use a `Type` like in pangeo-forge-runner: https://github.com/pangeo-forge/pangeo-forge-runner/blob/480d238cbb334162a907a1c8d1da5a27c50ffc6f/pangeo_forge_runner/commands/bake.py#L42 and instantiate it like this: https://github.com/pangeo-forge/pangeo-forge-runner/blob/480d238cbb334162a907a1c8d1da5a27c50ffc6f/pangeo_forge_runner/commands/bake.py#L132

**Comment by cisaacstern** [comment]
Perfect!! 🤩

**Comment by cisaacstern** [comment]
Per @sharkinsspatial's reminder in today's coordination meeting, this config overhaul should also smooth the pathway to a more extensible/pluggable bakery config (both compute and storage targets). This is mentioned in passing in the initial comment above, but just wanted to emphasize it here so I remember. This would be realized through setting config on orchestrator which is passed through to `pangeo-forge-runner` by the `Spawner` subclass.
